//
//  ArticleRepositoryTests.swift
//  KaifangShared
//
//  Created by Brendan Chen on 2026.06.01.
//

import Testing
import CoreData
@testable import KaifangCore

@Suite(.serialized)
struct ArticleRepositoryTests {
    // MARK: Type aliases
    typealias Tag = ArticleProvider.Tag
    typealias Author = ArticleProvider.Author
    typealias Article = ArticleProvider.Article
    typealias FilterArguments = ArticleProvider.FilterArguments
    typealias SortCriteria = ArticleProvider.SortCriteria
    typealias SentenceToken = SegmentationProvider.SentenceToken
    typealias WordToken = SegmentationProvider.WordToken
    
    // MARK: Setup
    private let container: NSPersistentContainer
    private let repository: ArticleRepository
    
    init() throws {
        container = try PersistenceController.getTestingContainer()
        repository = ArticleRepository(container: container)
    }
    
    // MARK: Data helpers
    func getSampleTags() -> Set<Tag> {
        [
            .init(id: UUID(), name: "Tag 3"),
            .init(id: UUID(), name: "Tag 2"),
            .init(id: UUID(), name: "Tag 1"),
        ]
    }
    
    func getSampleAuthors() -> Set<Author> {
        [
            .init(id: UUID(), name: "Author 3"),
            .init(id: UUID(), name: "Author 2"),
            .init(id: UUID(), name: "Author 1"),
        ]
    }
    
    func getSampleArticles() -> [Article] {
        // Generated by Claude
        
        let newsTag = Tag(id: UUID(), name: "News")
        let techTag = Tag(id: UUID(), name: "Tech")
        let cultureTag = Tag(id: UUID(), name: "Culture")

        let author1 = Author(id: UUID(), name: "Author 1")
        let author2 = Author(id: UUID(), name: "Author 2")
        let author3 = Author(id: UUID(), name: "Author 3")
        let author4 = Author(id: UUID(), name: "Author 4")

        // Keyword map for title/content filter tests. Articles mix SC and TC
        // around the English anchors to reflect realistic imported content.
        //   "Transit"   → Alpha title only
        //   "buses"     → Alpha content only
        //   "Quantum"   → Bravo title + content (same article)
        //   "量子"       → Bravo title + content (CJK form shared by SC/TC)
        //   "Festival"  → Charlie title only
        //   "dance"     → Charlie content only
        //   "舞蹈"       → Charlie content only (CJK form shared by SC/TC)
        //   "Markets"   → Delta title only
        //   "liquidity" → Delta content only
        //   "Evening"   → Echo title only
        //   "tonight"   → Echo content only
        //   "weekend"   → Charlie title + Delta content (two articles)
        //   "region"    → Alpha content + Echo title (two articles)
        return [
            // Shares `newsTag` with Article Bravo. Unread. Single author. SC body.
            .init(
                id: UUID(),
                plainText: "市议会一致通过新型 buses 巴士拨款议案。该决议将覆盖整个 region 城区的公共交通时间表。下周起新线路开始试运营。",
                title: "Alpha: Transit Budget 公共交通预算获市议会批准",
                datePublished: Date(timeIntervalSince1970: 1_700_000_000),
                dateRead: nil,
                tags: [newsTag],
                authors: [author1]
            ),
            // Bridges all three tags; read. Two authors, sharing `author1` with Alpha. TC body.
            .init(
                id: UUID(),
                plainText: "研究團隊在會議上展示了穩定的 quantum 量子處理器原型。新架構顯著提升了運算性能與糾錯能力。論文已於本週正式發表。",
                title: "Bravo: Quantum 量子計算重大突破",
                datePublished: Date(timeIntervalSince1970: 1_710_000_000),
                dateRead: Date(timeIntervalSince1970: 1_715_000_000),
                tags: [newsTag, techTag, cultureTag],
                authors: [author1, author2]
            ),
            // Shares `cultureTag` with Article Bravo. No publish date, unread. Co-authored. TC body.
            .init(
                id: UUID(),
                plainText: "傳統 dance 舞蹈與街頭藝術在開幕表演中亮相。藝術家們吸引了大批熱情的觀眾。活動將持續整整三天。",
                title: "Charlie: Weekend Festival 週末文化節亮點",
                datePublished: nil,
                dateRead: nil,
                tags: [cultureTag],
                authors: [author3, author4]
            ),
            // No tags. Read. `author1` reused again to exercise duplicate-author cases. SC body.
            .init(
                id: UUID(),
                plainText: "尽管 weekend 假期期间 liquidity 流动性紧张。主要指数仍稳步上扬。投资者保持谨慎乐观。",
                title: "Delta: Markets 股市稳步上扬",
                datePublished: Date(timeIntervalSince1970: 1_720_000_000),
                dateRead: Date(timeIntervalSince1970: 1_725_000_000),
                tags: [],
                authors: [author1]
            ),
            // No tags, no authors. Unread. SC body.
            .init(
                id: UUID(),
                plainText: "今晚 tonight 整个区域内目前没有重大事件。各部门保持正常运转。气象台预报明日转晴。",
                title: "Echo: Quiet Evening 宁静夜晚跨越 Region 全境",
                datePublished: Date(timeIntervalSince1970: 1_730_000_000),
                dateRead: nil,
                tags: [],
                authors: []
            ),
        ]
    }
    
    func generateSavedExpectedArticles() async throws -> [Article] {
        let articles = getSampleArticles()
        _ = try await repository.save(articles)

        return articles
    }

    /// Builds in-memory sentence tokens (with their embedded word tokens) for one of the sample
    /// articles produced by ``getSampleArticles()``. Does NOT persist anything; pair with
    /// ``ArticleRepository/saveSentenceTokens(_:forArticleId:)`` if persistence is needed.
    ///
    /// Each sample article maps to multiple ``SentenceToken``s — one per sentence in the body
    /// (at least three per article). Word tokens are hand-curated in left-to-right order within
    /// each sentence and exclude punctuation. ``SentenceToken/articleTextPositionStart`` is the
    /// UTF-16 offset of the sentence within ``ArticleProvider/Article/plainText``;
    /// ``WordToken/sentenceTextPositionStart`` is the UTF-16 offset of the word within its
    /// containing sentence (not the article). Lookup is by ``ArticleProvider/Article/plainText``
    /// since article IDs are regenerated on each ``getSampleArticles()`` call.
    func getSentenceTokensForArticle(article: Article) async throws -> [SentenceToken] {
        let plan: [(sentence: String, words: [String])]
        switch article.plainText {
        case "市议会一致通过新型 buses 巴士拨款议案。该决议将覆盖整个 region 城区的公共交通时间表。下周起新线路开始试运营。":
            plan = [
                (
                    sentence: "市议会一致通过新型 buses 巴士拨款议案。",
                    words: ["市议会", "一致", "通过", "新型", "buses", "巴士", "拨款", "议案"]
                ),
                (
                    sentence: "该决议将覆盖整个 region 城区的公共交通时间表。",
                    words: ["该", "决议", "将", "覆盖", "整个", "region", "城区", "的", "公共交通", "时间表"]
                ),
                (
                    sentence: "下周起新线路开始试运营。",
                    words: ["下周", "起", "新", "线路", "开始", "试", "运营"]
                ),
            ]
        case "研究團隊在會議上展示了穩定的 quantum 量子處理器原型。新架構顯著提升了運算性能與糾錯能力。論文已於本週正式發表。":
            plan = [
                (
                    sentence: "研究團隊在會議上展示了穩定的 quantum 量子處理器原型。",
                    words: ["研究", "團隊", "在", "會議", "上", "展示", "了", "穩定", "的", "quantum", "量子", "處理器", "原型"]
                ),
                (
                    sentence: "新架構顯著提升了運算性能與糾錯能力。",
                    words: ["新", "架構", "顯著", "提升", "了", "運算", "性能", "與", "糾錯", "能力"]
                ),
                (
                    sentence: "論文已於本週正式發表。",
                    words: ["論文", "已", "於", "本週", "正式", "發表"]
                ),
            ]
        case "傳統 dance 舞蹈與街頭藝術在開幕表演中亮相。藝術家們吸引了大批熱情的觀眾。活動將持續整整三天。":
            plan = [
                (
                    sentence: "傳統 dance 舞蹈與街頭藝術在開幕表演中亮相。",
                    words: ["傳統", "dance", "舞蹈", "與", "街頭", "藝術", "在", "開幕", "表演", "中", "亮相"]
                ),
                (
                    sentence: "藝術家們吸引了大批熱情的觀眾。",
                    words: ["藝術家", "們", "吸引", "了", "大批", "熱情", "的", "觀眾"]
                ),
                (
                    sentence: "活動將持續整整三天。",
                    words: ["活動", "將", "持續", "整整", "三", "天"]
                ),
            ]
        case "尽管 weekend 假期期间 liquidity 流动性紧张。主要指数仍稳步上扬。投资者保持谨慎乐观。":
            plan = [
                (
                    sentence: "尽管 weekend 假期期间 liquidity 流动性紧张。",
                    words: ["尽管", "weekend", "假期", "期间", "liquidity", "流动性", "紧张"]
                ),
                (
                    sentence: "主要指数仍稳步上扬。",
                    words: ["主要", "指数", "仍", "稳步", "上扬"]
                ),
                (
                    sentence: "投资者保持谨慎乐观。",
                    words: ["投资者", "保持", "谨慎", "乐观"]
                ),
            ]
        case "今晚 tonight 整个区域内目前没有重大事件。各部门保持正常运转。气象台预报明日转晴。":
            plan = [
                (
                    sentence: "今晚 tonight 整个区域内目前没有重大事件。",
                    words: ["今晚", "tonight", "整个", "区域", "内", "目前", "没有", "重大", "事件"]
                ),
                (
                    sentence: "各部门保持正常运转。",
                    words: ["各", "部门", "保持", "正常", "运转"]
                ),
                (
                    sentence: "气象台预报明日转晴。",
                    words: ["气象台", "预报", "明日", "转晴"]
                ),
            ]
        default:
            fatalError("No sample sentence tokens defined for article body: \(article.plainText)")
        }

        var sentenceTokens: [SentenceToken] = []
        var sentenceSearchStart = article.plainText.startIndex
        for (sentenceIndex, entry) in plan.enumerated() {
            guard let sentenceRange = article.plainText.range(
                of: entry.sentence,
                range: sentenceSearchStart..<article.plainText.endIndex
            ) else {
                fatalError("Sentence '\(entry.sentence)' not found in article body '\(article.plainText)'.")
            }
            let articleUtf16Start = article.plainText.utf16.distance(
                from: article.plainText.utf16.startIndex,
                to: sentenceRange.lowerBound.samePosition(in: article.plainText.utf16)!
            )

            var wordTokens: [WordToken] = []
            var wordSearchStart = entry.sentence.startIndex
            for (wordIndex, word) in entry.words.enumerated() {
                guard let wordRange = entry.sentence.range(
                    of: word,
                    range: wordSearchStart..<entry.sentence.endIndex
                ) else {
                    fatalError("Word '\(word)' not found in sentence '\(entry.sentence)'.")
                }
                let sentenceUtf16Start = entry.sentence.utf16.distance(
                    from: entry.sentence.utf16.startIndex,
                    to: wordRange.lowerBound.samePosition(in: entry.sentence.utf16)!
                )
                wordTokens.append(
                    WordToken(
                        id: UUID(),
                        tokenText: word,
                        sentenceTextPositionStart: Int32(sentenceUtf16Start),
                        wordIndexInSentence: Int32(wordIndex)
                    )
                )
                wordSearchStart = wordRange.upperBound
            }

            sentenceTokens.append(
                SentenceToken(
                    id: UUID(),
                    articleTextPositionStart: Int32(articleUtf16Start),
                    sentenceIndexInArticle: Int32(sentenceIndex),
                    tokenText: entry.sentence,
                    wordTokens: wordTokens
                )
            )
            sentenceSearchStart = sentenceRange.upperBound
        }

        return sentenceTokens
    }

    func getDefaultSortCriteria() async throws -> SortCriteria {
        .title(.forward)
    }
    
    // MARK: Tags and authors
    
    @Test("Getting all tags gets them in a set")
    func getTagsReturnsAllTagsInSet() async throws {
        let expectedTags = getSampleTags()
        _ = try await repository.saveTags(expectedTags)
        
        let resultingTags = try await repository.getTags()
        #expect(resultingTags.count == 3)
        #expect(resultingTags.contains { $0.name == "Tag 2" })
        #expect(resultingTags.contains { $0.name == "Tag 1" })
        #expect(resultingTags.contains { $0.name == "Tag 3" })
    }
    
    @Test("Getting all authors gets them in a set")
    func getAuthorsReturnsAllAuthorsInSet() async throws {
        let expectedAuthors = getSampleAuthors()
        _ = try await repository.saveAuthors(expectedAuthors)
        
        let resultingAuthors = try await repository.getAuthors()
        #expect(resultingAuthors.count == 3)
        #expect(resultingAuthors.contains { $0.name == "Author 2" })
        #expect(resultingAuthors.contains { $0.name == "Author 1" })
        #expect(resultingAuthors.contains { $0.name == "Author 3" })
    }
    
    @Test("Getting all tags returns an empty set if no tags exist")
    func getTagsReturnsEmptySetIfNonexistent() async throws {
        let tags = try await repository.getTags()
        #expect(tags.isEmpty)
    }
    
    @Test("Getting all authors returns an empty set if no authors exist")
    func getAuthorsReturnsEmptySetIfNonexistent() async throws {
        let authors = try await repository.getAuthors()
        #expect(authors.isEmpty)
    }
    
    // MARK: Filtering and sorting
    
    // note that tag filter tests require a different shape than title/content filters, since
    // tags are their own data entity
    
    @Test(
        "Filtering filters by tags",
        arguments: [
            "News",
            "Tech",
            "Culture"
        ]
    )
    func filterFiltersByTags(
        tagName: String
    ) async throws {
        let expectedArticles = try await generateSavedExpectedArticles().filter {
            $0.tags.contains {
                $0.name.localizedStandardCompare(tagName) == .orderedSame
            }
        }.sorted {
            $0.title.localizedCompare($1.title) == .orderedAscending
        }
        try #require(expectedArticles.count > 0)
        
        let tags = try await repository.getTags()
        let tag = tags.first { $0.name.localizedStandardCompare(tagName) == .orderedSame }
        try #require(tag != nil)
        
        let filterArgs = FilterArguments(
            tags: Set([tag!]),
            titleAndContents: nil,
            unreadOnly: nil
        )
        let sortArg: SortCriteria = .title(.forward)
        
        let resultingArticles = try await repository.list(
            filterBy: filterArgs,
            sortBy: sortArg
        )
        #expect(expectedArticles == resultingArticles)
    }
    
    @Test(
        "Filtering title/contents filters by title and content, with case insensitivity",
        arguments: ["weekend", "region", "Markets", "liquidity", "Festival", "dance"]
    )
    func filterByTitleAndContentsFiltersTitleAndContents(keyword: String) async throws {
        let expectedArticles = try await generateSavedExpectedArticles().filter {
            $0.title.localizedCaseInsensitiveContains(keyword) || $0.plainText.localizedCaseInsensitiveContains(keyword)
        }.sorted {
            $0.title.localizedCompare($1.title) == .orderedAscending
        }
        try #require(expectedArticles.count > 0)
        
        let filterArgs = FilterArguments(
            tags: nil,
            titleAndContents: keyword,
            unreadOnly: nil
        )
        
        let resultingArticles = try await repository.list(
            filterBy: filterArgs,
            sortBy: getDefaultSortCriteria()
        )
        #expect(expectedArticles == resultingArticles)
    }
    
    @Test("Filtering by unread only filters out read articles")
    func filterByUnreadOnlyFiltersOutReadArticles() async throws {
        let expectedArticles = try await generateSavedExpectedArticles().filter {
            $0.dateRead == nil
        }.sorted {
            $0.title.localizedCompare($1.title) == .orderedAscending
        }
        try #require(expectedArticles.count > 0)
        
        let filterArgs = FilterArguments(
            tags: nil,
            titleAndContents: nil,
            unreadOnly: true  // false is same behavior as nil
        )
        
        let resultingArticles = try await repository.list(
            filterBy: filterArgs,
            sortBy: getDefaultSortCriteria()
        )
        #expect(expectedArticles == resultingArticles)
    }
    
    @Test("Filtering by no properties returns all articles")
    func filterByNoPropertiesReturnsAllArticles() async throws {
        let expectedArticles = try await generateSavedExpectedArticles()
        
        let filterArgs = FilterArguments(
            tags: nil,
            titleAndContents: nil,
            unreadOnly: nil
        )

        let resultingArticles = try await repository.list(
            filterBy: filterArgs,
            sortBy: getDefaultSortCriteria()
        )
        #expect(expectedArticles == resultingArticles)
    }
    
    struct SortCase: Sendable {
        let name: String
        let sortBy: @Sendable (Article, Article) -> Bool
        let criteria: SortCriteria
    }
    
    @Test(
        "Sorting criteria meets expected expected sort orders",
        arguments: [
            SortCase(
                name: "Sorting by article title orders from A to Z",
                sortBy: { $0.title.localizedCompare($1.title) == .orderedAscending },
                criteria: .title(.forward)
            ),
            SortCase(
                name: "Sorting by article title orders from Z to A",
                sortBy: { $0.title.localizedCompare($1.title) == .orderedDescending },
                criteria: .title(.reverse)
            ),
            SortCase(
                name: "Sorting by date modified orders from earliest to latest",
                sortBy: { $0.dateModified < $1.dateModified },
                criteria: .dateModified(.forward)
            ),
            SortCase(
                name: "Sorting by date modified orders from latest to earliest",
                sortBy: { $0.dateModified > $1.dateModified },
                criteria: .dateModified(.reverse)
            ),
            SortCase(
                name: "Sorting by date created orders from earliest to latest",
                sortBy: { $0.dateCreated < $1.dateCreated },
                criteria: .dateCreated(.forward)
            ),
            SortCase(
                name: "Sorting by date created orders from latest to earliest",
                sortBy: { $0.dateCreated > $1.dateCreated },
                criteria: .dateCreated(.reverse)
            ),
        ]
    )
    func sortingCriteriaMeetsExpectedSortOrders(sortCase: SortCase) async throws {
        let expectedArticles = try await generateSavedExpectedArticles().sorted(by: sortCase.sortBy)
        
        let filterArgs = FilterArguments(
            tags: nil,
            titleAndContents: nil,
            unreadOnly: nil
        )
        let sortArg = sortCase.criteria
        
        let resultingArticles = try await repository.list(
            filterBy: filterArgs,
            sortBy: sortArg
        )
        #expect(expectedArticles == resultingArticles)
    }
    
    @Test("Finding an article by UUID returns the article if found")
    func findReturnsArticle() async throws {
        let articles = try await generateSavedExpectedArticles()
        let expectedArticle = articles[0]
        
        let resultArticle = try await repository.find(expectedArticle.id)
        #expect(resultArticle == expectedArticle)
    }
    
    @Test("Finding an article by UUID returns nil if the article is not found")
    func findReturnsNilIfNotFound() async throws {
        let resultArticle = try await repository.find(UUID())
        #expect(resultArticle == nil)
    }
    
    @Test("Getting the sentence tokens for an article returns an empty array if they don't exist")
    func getSentenceTokensReturnsEmptyArrayIfNonexistent() async throws {
        let articles = try await generateSavedExpectedArticles()
        let article = articles[0]
        
        let resultSentenceTokens = try await repository.getSentenceTokens(forArticleId: article.id)
        #expect(resultSentenceTokens.isEmpty)
    }
    
    @Test("Getting the sentence tokens for an article throws if the article doesn't exist")
    func getSentenceTokensThrowsIfArticleDoesNotExist() async throws {
        await #expect(throws: ArticleProvider.Error.notFound) {
            try await repository.getSentenceTokens(forArticleId: UUID())
        }
    }
    
    @Test("Saving and getting the sentence tokens for an article returns the sentence tokens ordered by index")
    func getSentenceTokensReturnsOrderedSentenceTokensIfExists() async throws {
        let articles = try await generateSavedExpectedArticles()
        
        for article in articles {
            // note that sentence tokens passed to save may not be in index order
            var sentenceTokens = try await getSentenceTokensForArticle(article: article)
            sentenceTokens = try await repository.saveSentenceTokens(sentenceTokens, forArticleId: article.id)
            
            let resultTokens = try await repository.getSentenceTokens(forArticleId: article.id)
            #expect(sentenceTokens == resultTokens)
        }
    }
    
    @Test("Saving the sentence tokens for an article updates existing tokens and saves new ones")
    func saveSentenceTokensUpdatesExistingTokensAndSavesNewOnes() async throws {
        let articles = try await generateSavedExpectedArticles()
        
        for article in articles {
            var sentenceTokens = try await getSentenceTokensForArticle(article: article)
            
            // first save
            var firstSaveSentenceTokens = [sentenceTokens[0], sentenceTokens[2]]
            firstSaveSentenceTokens = try await repository.saveSentenceTokens(firstSaveSentenceTokens, forArticleId: article.id)
            
            // simulate a modification of an existing token, then save all tokens
            sentenceTokens[0] = SentenceToken(
                id: sentenceTokens[0].id,
                articleTextPositionStart: sentenceTokens[0].articleTextPositionStart,
                sentenceIndexInArticle: sentenceTokens[0].sentenceIndexInArticle,
                tokenText: "Updated text",
                wordTokens: [
                    .init(
                        id: UUID(),
                        tokenText: "Updated",
                        sentenceTextPositionStart: 0,
                        wordIndexInSentence: 0,
                    ),
                    .init(
                        id: UUID(),
                        tokenText: "text",
                        sentenceTextPositionStart: 8,
                        wordIndexInSentence: 1
                    )
                ],
            )
            
            // second save
            sentenceTokens = try await repository.saveSentenceTokens(sentenceTokens, forArticleId: article.id)
            
            let resultTokens = try await repository.getSentenceTokens(forArticleId: article.id)
            #expect(resultTokens == sentenceTokens.sorted { $0.sentenceIndexInArticle < $1.sentenceIndexInArticle })
        }
    }
    
    @Test("Saving sentence tokens throws error if there is an index collision of a new sentence token with an existing one")
    func saveSentenceTokensThrowsIfIndexCollisionOfNewWithExisting() async throws {
        let articles = try await generateSavedExpectedArticles()
        
        for article in articles {
            var sentenceTokens = try await getSentenceTokensForArticle(article: article)
            let count = sentenceTokens.count
            sentenceTokens = try await repository.saveSentenceTokens(sentenceTokens, forArticleId: article.id)
            try #require(sentenceTokens.count == count)
            
            sentenceTokens[0] = .init(
                id: UUID(),  // criteria for "new" is just that the ID is different
                articleTextPositionStart: sentenceTokens[0].articleTextPositionStart,
                sentenceIndexInArticle: 0,
                tokenText: sentenceTokens[0].tokenText,
                wordTokens: sentenceTokens[0].wordTokens
            )
            
            await #expect(throws: SegmentationProvider.Error.tokenAlreadyExistsAtIndex(index: 0)) {
                try await repository.saveSentenceTokens(sentenceTokens, forArticleId: article.id)
            }
        }
    }
    
    @Test("Saving and getting sentence tokens returns a collection ordered by the stored index")
    func saveAndGetSentenceTokensReturnsCollectionOrderedByStoredIndex() async throws {
        let articles = try await generateSavedExpectedArticles()
        
        for article in articles {
            var sentenceTokens = try await getSentenceTokensForArticle(article: article)
            let expectedSentenceTokens = sentenceTokens
            sentenceTokens.shuffle()
            
            sentenceTokens = try await repository.saveSentenceTokens(sentenceTokens, forArticleId: article.id)
            #expect(sentenceTokens == expectedSentenceTokens)
            
            let resultSentenceTokens = try await repository.getSentenceTokens(forArticleId: article.id)
            #expect(resultSentenceTokens == expectedSentenceTokens)
        }
    }
    
    @Test("Saving and getting sentence tokens returns nested word tokens that are ordered by the stored index")
    func saveAndGetSentenceTokensReturnsWordTokensOrderedByStoredIndex() async throws {
        let articles = try await generateSavedExpectedArticles()
        
        for article in articles {
            var sentenceTokens = try await getSentenceTokensForArticle(article: article)
            let expectedSentenceTokens = sentenceTokens
            sentenceTokens[0] = SentenceToken(
                id: sentenceTokens[0].id,
                articleTextPositionStart: sentenceTokens[0].articleTextPositionStart,
                sentenceIndexInArticle: sentenceTokens[0].sentenceIndexInArticle,
                tokenText: sentenceTokens[0].tokenText,
                wordTokens: sentenceTokens[0].wordTokens.shuffled(),
            )
            sentenceTokens = try await repository.saveSentenceTokens(sentenceTokens, forArticleId: article.id)
            #expect(sentenceTokens == expectedSentenceTokens)
            
            let resultSentenceTokens = try await repository.getSentenceTokens(forArticleId: article.id)
            #expect(resultSentenceTokens == expectedSentenceTokens)
        }
    }
    
    @Test("Clearing sentence tokens clears all of the sentence tokens associated with the article")
    func clearSentenceTokensClearsForOneArticleOnly() async throws {
        let articles = try await generateSavedExpectedArticles()
        
        // test sentence tokens for multiple articles, and try clearing just one set
        for article in articles {
            let sentenceTokens = try await getSentenceTokensForArticle(article: article)
            _ = try await repository.saveSentenceTokens(sentenceTokens, forArticleId: article.id)
        }
        
        guard let first = articles.first else {
            Issue.record("First article is missing.")
            return
        }
        
        try await repository.clearSentenceTokens(forArticleId: first.id)
        
        let otherArticles = articles[1...]
        for article in otherArticles {
            let sentenceTokens = try await repository.getSentenceTokens(forArticleId: article.id)
            #expect(sentenceTokens.count > 0)
        }
    }
    
    @Test("Saving an individual existing article updates its metadata")
    func saveUpdatesExistingArticle() async throws {
        var articles = try await generateSavedExpectedArticles()
        
        for i in 0..<articles.count {
            let article = articles[i]
            let updatedArticle = Article(
                id: article.id,
                plainText: "Updated plain text",
                title: "Updated title \(i)",
                datePublished: nil,
                dateRead: nil,
                tags: [],
                authors: []
            )
            articles[i] = updatedArticle
            
            _ = try await repository.save(updatedArticle)
        }
        
        let resultArticles = try await repository.list(
            filterBy: FilterArguments(
                tags: nil,
                titleAndContents: nil,
                unreadOnly: nil
            ),
            sortBy: .title(.forward)
        )
        #expect(resultArticles == articles)
    }
    
    @Test("Saving an individual new article creates it")
    func saveCreatesNewArticle() async throws {
        let articles = getSampleArticles()
        
        for article in articles {
            let article = try await repository.save(article)
            let resultArticle = try await repository.find(article.id)
            #expect(resultArticle == article)
        }
    }
    
    @Test("Saving a new individual article with tags creates any new tags")
    func saveWithTagsCreatesNewTags() async throws {
        var existingTags = getSampleTags()
        existingTags = try await repository.saveTags(existingTags)
        try #require(existingTags.count > 0)
        
        let articles = getSampleArticles()
        guard let article = articles.first else {
            Issue.record("No sample articles.")
            return
        }
        
        var tags = article.tags
        tags.formUnion(existingTags)
        
        _ = try await repository.save(article)
        
        let resultTags = try await repository.getTags()
        #expect(resultTags == tags)
    }
    
    @Test("Saving a new individual article with tags having conflicting names with existing tags throws")
    func saveWithTagsHavingConflictingNamesThrows() async throws {
        // pre-existing tag named "News" with its own ID; the sample articles include a `newsTag`
        // with a different ID but the same name → conflict on save.
        let conflictingTagName = "News"
        let existingTag = Tag(id: UUID(), name: conflictingTagName)
        _ = try await repository.saveTags([existingTag])

        let articles = getSampleArticles()
        guard let article = articles.first(where: { article in
            article.tags.contains { $0.name == conflictingTagName }
        }) else {
            Issue.record("No sample article has a tag named \(conflictingTagName).")
            return
        }
        try #require(!article.tags.contains { $0.id == existingTag.id })

        await #expect(throws: ArticleProvider.Error.tagNameConflict(name: conflictingTagName)) {
            _ = try await repository.save(article)
        }
    }

    @Test("Saving a new individual article with authors having conflicting names with existing authors throws")
    func saveWithAuthorsHavingConflictingNamesThrows() async throws {
        let conflictingAuthorName = "Author 1"
        let existingAuthor = Author(id: UUID(), name: conflictingAuthorName)
        _ = try await repository.saveAuthors([existingAuthor])

        let articles = getSampleArticles()
        guard let article = articles.first(where: { article in
            article.authors.contains { $0.name == conflictingAuthorName }
        }) else {
            Issue.record("No sample article has an author named \(conflictingAuthorName).")
            return
        }
        try #require(!article.authors.contains { $0.id == existingAuthor.id })

        await #expect(throws: ArticleProvider.Error.authorNameConflict(name: conflictingAuthorName)) {
            _ = try await repository.save(article)
        }
    }

    @Test("Saving multiple articles with tags having conflicting names with existing tags throws")
    func saveMultipleWithTagsHavingConflictingNamesThrows() async throws {
        let conflictingTagName = "News"
        let existingTag = Tag(id: UUID(), name: conflictingTagName)
        _ = try await repository.saveTags([existingTag])

        let articles = getSampleArticles()
        try #require(articles.contains { article in
            article.tags.contains { $0.name == conflictingTagName && $0.id != existingTag.id }
        })

        await #expect(throws: ArticleProvider.Error.tagNameConflict(name: conflictingTagName)) {
            _ = try await repository.save(articles)
        }
    }

    @Test("Saving multiple articles with authors having conflicting names with existing authors throws")
    func saveMultipleWithAuthorsHavingConflictingNamesThrows() async throws {
        let conflictingAuthorName = "Author 1"
        let existingAuthor = Author(id: UUID(), name: conflictingAuthorName)
        _ = try await repository.saveAuthors([existingAuthor])

        let articles = getSampleArticles()
        try #require(articles.contains { article in
            article.authors.contains { $0.name == conflictingAuthorName && $0.id != existingAuthor.id }
        })

        await #expect(throws: ArticleProvider.Error.authorNameConflict(name: conflictingAuthorName)) {
            _ = try await repository.save(articles)
        }
    }

    @Test("Saving a list of articles where some already exist updates the existing ones, and creates the new ones")
    func saveMultipleWithSomeExistingUpdatesExistingAndCreatesNew() async throws {
        var articles = try await generateSavedExpectedArticles()

        // update the first two pre-existing articles in place (same id, different metadata)
        for i in 0..<2 {
            articles[i] = Article(
                id: articles[i].id,
                plainText: "Updated plain text \(i)",
                title: "Updated title \(i)",
                datePublished: nil,
                dateRead: nil,
                tags: [],
                authors: []
            )
        }

        // tack on two brand-new articles
        let newArticles: [Article] = [
            .init(
                id: UUID(),
                plainText: "Brand new article body one.",
                title: "Yankee: New Article One",
                datePublished: nil,
                dateRead: nil,
                tags: [],
                authors: []
            ),
            .init(
                id: UUID(),
                plainText: "Brand new article body two.",
                title: "Zulu: New Article Two",
                datePublished: nil,
                dateRead: nil,
                tags: [],
                authors: []
            ),
        ]

        let combined = articles + newArticles
        _ = try await repository.save(combined)

        let resultArticles = try await repository.list(
            filterBy: FilterArguments(tags: nil, titleAndContents: nil, unreadOnly: nil),
            sortBy: getDefaultSortCriteria()
        )
        let expectedSorted = combined.sorted { $0.title.localizedCompare($1.title) == .orderedAscending }
        #expect(resultArticles == expectedSorted)
    }

    @Test("Deleting an article deletes the article")
    func deleteDeletesTheArticle() async throws {
        let articles = try await generateSavedExpectedArticles()
        guard let articleToDelete = articles.first else {
            Issue.record("No articles to delete.")
            return
        }

        try await repository.delete(id: articleToDelete.id)

        let resultArticle = try await repository.find(articleToDelete.id)
        #expect(resultArticle == nil)
    }

    @Test("Deleting an article also deletes its sentence tokens")
    func deleteDeletesSentenceTokens() async throws {
        let articles = try await generateSavedExpectedArticles()
        guard let article = articles.first else {
            Issue.record("No articles to delete.")
            return
        }

        let sentenceTokens = try await getSentenceTokensForArticle(article: article)
        _ = try await repository.saveSentenceTokens(sentenceTokens, forArticleId: article.id)

        try await repository.delete(id: article.id)

        await #expect(throws: ArticleProvider.Error.notFound) {
            _ = try await repository.getSentenceTokens(forArticleId: article.id)
        }
    }

    @Test("Deleting an article also deletes associated tags if no more articles point to them")
    func deleteDeletesAssociatedTagsIfNoArticlesPointToThem() async throws {
        let articles = try await generateSavedExpectedArticles()

        // Bravo carries [News, Tech, Culture]. Deleting it orphans only Tech — News is still held
        // by Alpha and Culture is still held by Charlie.
        guard let bravo = articles.first(where: { $0.title.hasPrefix("Bravo") }) else {
            Issue.record("Bravo article missing from sample set.")
            return
        }

        let tagsBefore = try await repository.getTags()
        try #require(tagsBefore.contains { $0.name == "Tech" })
        try #require(tagsBefore.contains { $0.name == "News" })
        try #require(tagsBefore.contains { $0.name == "Culture" })

        try await repository.delete(id: bravo.id)

        let tagsAfter = try await repository.getTags()
        #expect(!tagsAfter.contains { $0.name == "Tech" })
        #expect(tagsAfter.contains { $0.name == "News" })
        #expect(tagsAfter.contains { $0.name == "Culture" })
    }

    @Test("Deleting an article does not delete associated authors even if no more articles point to them")
    func deleteDoesNotDeleteAssociatedAuthors() async throws {
        let articles = try await generateSavedExpectedArticles()

        // Charlie's [author3, author4] are unique to Charlie among the sample set. After deleting
        // Charlie, both authors should still exist even though no article references them.
        guard let charlie = articles.first(where: { $0.title.hasPrefix("Charlie") }) else {
            Issue.record("Charlie article missing from sample set.")
            return
        }
        let charlieAuthorNames = Set(charlie.authors.map(\.name))
        try #require(!charlieAuthorNames.isEmpty)

        try await repository.delete(id: charlie.id)

        let remainingAuthorNames = Set(try await repository.getAuthors().map(\.name))
        #expect(charlieAuthorNames.isSubset(of: remainingAuthorNames))
    }

    @Test("Deleting an article throws if the article is not found")
    func deleteThrowsIfNotFound() async throws {
        await #expect(throws: ArticleProvider.Error.notFound) {
            try await repository.delete(id: UUID())
        }
    }
}
