//
//  ArticleRepositoryTests.swift
//  KaifangShared
//
//  Created by Brendan Chen on 2026.06.01.
//

import Testing
import CoreData
@testable import KaifangCore

@Suite(.serialized)
struct ArticleRepositoryTests {
    // MARK: Type aliases
    typealias Tag = ArticleProvider.Tag
    typealias Author = ArticleProvider.Author
    typealias Article = ArticleProvider.Article
    typealias FilterArguments = ArticleProvider.FilterArguments
    typealias SortCriteria = ArticleProvider.SortCriteria
    
    // MARK: Setup
    private let container: NSPersistentContainer
    private let repository: ArticleRepository
    
    init() throws {
        container = try PersistenceController.getTestingContainer()
        repository = ArticleRepository(container: container)
    }
    
    // MARK: Data helpers
    func getSampleTags() -> Set<Tag> {
        [
            .init(id: UUID(), name: "Tag 3"),
            .init(id: UUID(), name: "Tag 2"),
            .init(id: UUID(), name: "Tag 1"),
        ]
    }
    
    func getSampleAuthors() -> Set<Author> {
        [
            .init(id: UUID(), name: "Author 3"),
            .init(id: UUID(), name: "Author 2"),
            .init(id: UUID(), name: "Author 1"),
        ]
    }
    
    func getSampleArticles() -> [Article] {
        // Generated by Claude
        
        let newsTag = Tag(id: UUID(), name: "News")
        let techTag = Tag(id: UUID(), name: "Tech")
        let cultureTag = Tag(id: UUID(), name: "Culture")

        let author1 = Author(id: UUID(), name: "Author 1")
        let author2 = Author(id: UUID(), name: "Author 2")
        let author3 = Author(id: UUID(), name: "Author 3")
        let author4 = Author(id: UUID(), name: "Author 4")

        // Keyword map for title/content filter tests. Articles mix SC and TC
        // around the English anchors to reflect realistic imported content.
        //   "Transit"   → Alpha title only
        //   "buses"     → Alpha content only
        //   "Quantum"   → Bravo title + content (same article)
        //   "量子"       → Bravo title + content (CJK form shared by SC/TC)
        //   "Festival"  → Charlie title only
        //   "dance"     → Charlie content only
        //   "舞蹈"       → Charlie content only (CJK form shared by SC/TC)
        //   "Markets"   → Delta title only
        //   "liquidity" → Delta content only
        //   "Evening"   → Echo title only
        //   "tonight"   → Echo content only
        //   "weekend"   → Charlie title + Delta content (two articles)
        //   "region"    → Alpha content + Echo title (two articles)
        return [
            // Shares `newsTag` with Article Bravo. Unread. Single author. SC body.
            .init(
                id: UUID(),
                plainText: "市议会一致通过新 buses 巴士拨款,覆盖整个 region 城区。",
                title: "Alpha: Transit Budget 公共交通预算获市议会批准",
                datePublished: Date(timeIntervalSince1970: 1_700_000_000),
                dateRead: nil,
                tags: [newsTag],
                authors: [author1]
            ),
            // Bridges all three tags; read. Two authors, sharing `author1` with Alpha. TC body.
            .init(
                id: UUID(),
                plainText: "研究團隊展示了穩定的 quantum 量子處理器原型。",
                title: "Bravo: Quantum 量子計算重大突破",
                datePublished: Date(timeIntervalSince1970: 1_710_000_000),
                dateRead: Date(timeIntervalSince1970: 1_715_000_000),
                tags: [newsTag, techTag, cultureTag],
                authors: [author1, author2]
            ),
            // Shares `cultureTag` with Article Bravo. No publish date, unread. Co-authored. TC body.
            .init(
                id: UUID(),
                plainText: "傳統 dance 舞蹈與街頭藝術吸引了大批人群。",
                title: "Charlie: Weekend Festival 週末文化節亮點",
                datePublished: nil,
                dateRead: nil,
                tags: [cultureTag],
                authors: [author3, author4]
            ),
            // No tags. Read. `author1` reused again to exercise duplicate-author cases. SC body.
            .init(
                id: UUID(),
                plainText: "尽管 weekend 期间 liquidity 流动性紧张,指数仍稳步上扬。",
                title: "Delta: Markets 股市稳步上扬",
                datePublished: Date(timeIntervalSince1970: 1_720_000_000),
                dateRead: Date(timeIntervalSince1970: 1_725_000_000),
                tags: [],
                authors: [author1]
            ),
            // No tags, no authors. Unread. SC body.
            .init(
                id: UUID(),
                plainText: "今晚 tonight 区域内没有重大事件报告。",
                title: "Echo: Quiet Evening 宁静夜晚跨越 Region 全境",
                datePublished: Date(timeIntervalSince1970: 1_730_000_000),
                dateRead: nil,
                tags: [],
                authors: []
            ),
        ]
    }
    
    func generateSavedExpectedArticles() async throws -> [Article] {
        let articles = getSampleArticles()
        _ = try await repository.save(articles)

        return articles
    }
    
    func getDefaultSortCriteria() async throws -> SortCriteria {
        .title(.forward)
    }
    
    // MARK: Tags and authors
    
    @Test("Getting all tags gets them in a set")
    func getTagsReturnsInAlphabeticalOrder() async throws {
        let expectedTags = getSampleTags()
        _ = try await repository.saveTags(expectedTags)
        
        let resultingTags = try await repository.getTags()
        #expect(resultingTags.count == 3)
        #expect(resultingTags.contains { $0.name == "Tag 2" })
        #expect(resultingTags.contains { $0.name == "Tag 1" })
        #expect(resultingTags.contains { $0.name == "Tag 3" })
    }
    
    @Test("Getting all authors gets them in a set")
    func getAuthorsReturnsInAlphabeticalOrder() async throws {
        let expectedAuthors = getSampleAuthors()
        _ = try await repository.saveAuthors(expectedAuthors)
        
        let resultingAuthors = try await repository.getAuthors()
        #expect(resultingAuthors.count == 3)
        #expect(resultingAuthors.contains { $0.name == "Author 2" })
        #expect(resultingAuthors.contains { $0.name == "Author 1" })
        #expect(resultingAuthors.contains { $0.name == "Author 3" })
    }
    
    @Test("Getting all tags returns empty array if no tags exist")
    func getTagsReturnsEmptyArrayIfNonexistent() async throws {
        let tags = try await repository.getTags()
        #expect(tags.isEmpty)
    }
    
    @Test("Getting all authors returns empty array if no authors exist")
    func getAuthorsReturnsEmptyArrayIfNonexistent() async throws {
        let authors = try await repository.getAuthors()
        #expect(authors.isEmpty)
    }
    
    // MARK: Filtering and sorting
    
    // note that tag filter tests require a different shape than title/content filters, since
    // tags are their own data entity
    
    @Test(
        "Filtering filters by tags",
        arguments: [
            "News",
            "Tech",
            "Culture"
        ]
    )
    func filterFiltersByTags(
        tagName: String
    ) async throws {
        let expectedArticles = try await generateSavedExpectedArticles().filter {
            $0.tags.contains {
                $0.name.localizedStandardCompare(tagName) == .orderedSame
            }
        }.sorted {
            $0.title < $1.title
        }
        try #require(expectedArticles.count > 0)
        
        let tags = try await repository.getTags()
        let tag = tags.first { $0.name.localizedStandardCompare(tagName) == .orderedSame }
        try #require(tag != nil)
        
        let filterArgs = FilterArguments(
            tags: Set([tag!]),
            titleAndContents: nil,
            unreadOnly: nil
        )
        let sortArg: SortCriteria = .title(.forward)
        
        let resultingArticles = try await repository.list(
            filterBy: filterArgs,
            sortBy: sortArg
        )
        #expect(expectedArticles == resultingArticles)
    }
    
    @Test(
        "Filtering title/contents filters by title and content, with case insensitivity",
        arguments: ["weekend", "region", "Markets", "liquidity", "Festival", "dance"]
    )
    func filterByTitleAndContentsFiltersTitleAndContents(keyword: String) async throws {
        let expectedArticles = try await generateSavedExpectedArticles().filter {
            $0.title.localizedCaseInsensitiveContains(keyword) || $0.plainText.localizedCaseInsensitiveContains(keyword)
        }.sorted {
            $0.title < $1.title
        }
        try #require(expectedArticles.count > 0)
        
        let filterArgs = FilterArguments(
            tags: nil,
            titleAndContents: keyword,
            unreadOnly: nil
        )
        
        let resultingArticles = try await repository.list(
            filterBy: filterArgs,
            sortBy: getDefaultSortCriteria()
        )
        #expect(expectedArticles == resultingArticles)
    }
    
    @Test("Filtering by unread only filters out read articles")
    func filterByUnreadOnlyFiltersOutReadArticles() async throws {
        let expectedArticles = try await generateSavedExpectedArticles().filter {
            $0.dateRead != nil
        }.sorted {
            $0.title < $1.title
        }
        try #require(expectedArticles.count > 0)
        
        let filterArgs = FilterArguments(
            tags: nil,
            titleAndContents: nil,
            unreadOnly: true  // false is same behavior as nil
        )
        
        let resultingArticles = try await repository.list(
            filterBy: filterArgs,
            sortBy: getDefaultSortCriteria()
        )
        #expect(expectedArticles == resultingArticles)
    }
    
    @Test("Filtering by no properties returns all articles")
    func filterByNoPropertiesReturnsAllArticles() async throws {
        let expectedArticles = try await generateSavedExpectedArticles()
        
        let filterArgs = FilterArguments(
            tags: nil,
            titleAndContents: nil,
            unreadOnly: nil
        )

        let resultingArticles = try await repository.list(
            filterBy: filterArgs,
            sortBy: getDefaultSortCriteria()
        )
        #expect(expectedArticles == resultingArticles)
    }
    
    struct SortCase: Sendable {
        let name: String
        let sortBy: @Sendable (Article, Article) -> Bool
        let criteria: SortCriteria
    }
    
    @Test(
        "Sorting criteria meets expected expected sort orders",
        arguments: [
            SortCase(
                name: "Sorting by article title orders from A to Z",
                sortBy: { $0.title.localizedCompare($1.title) == .orderedAscending },
                criteria: .title(.forward)
            ),
            SortCase(
                name: "Sorting by article title orders from Z to A",
                sortBy: { $0.title.localizedCompare($1.title) == .orderedDescending },
                criteria: .title(.reverse)
            ),
            SortCase(
                name: "Sorting by date modified orders from earliest to latest",
                sortBy: { $0.dateModified < $1.dateModified },
                criteria: .dateModified(.forward)
            ),
            SortCase(
                name: "Sorting by date modified orders from latest to earliest",
                sortBy: { $0.dateModified > $1.dateModified },
                criteria: .dateModified(.reverse)
            ),
            SortCase(
                name: "Sorting by date created orders from earliest to latest",
                sortBy: { $0.dateCreated < $1.dateCreated },
                criteria: .dateCreated(.forward)
            ),
            SortCase(
                name: "Sorting by date created orders from latest to earliest",
                sortBy: { $0.dateCreated > $1.dateCreated },
                criteria: .dateCreated(.reverse)
            ),
        ]
    )
    func sortingCriteriaMeetsExpectedSortOrders(sortCase: SortCase) async throws {
        let expectedArticles = try await generateSavedExpectedArticles().sorted(by: sortCase.sortBy)
        
        let filterArgs = FilterArguments(
            tags: nil,
            titleAndContents: nil,
            unreadOnly: nil
        )
        let sortArg = sortCase.criteria
        
        let resultingArticles = try await repository.list(
            filterBy: filterArgs,
            sortBy: sortArg
        )
        #expect(expectedArticles == resultingArticles)
    }
    
    @Test("Finding an article by UUID returns the article if found")
    func findReturnsArticle() async throws {
        
    }
    
    @Test("Finding an article by UUID returns nil if the article is not found")
    func findReturnsNilIfNotFound() async throws {
        
    }
    
    @Test("Getting the sentence tokens for an article returns an empty array if they don't exist")
    func getSentenceTokensReturnsNilIfNonexistent() async throws {
        
    }
    
    @Test("Getting the sentence tokens for an article returns the sentence tokens ordered by index")
    func getSentenceTokensReturnsOrderedSentenceTokensIfExists() async throws {
        
    }
    
    @Test("Saving the sentence tokens for an article updates existing tokens and saves new ones")
    func saveSentenceTokensUpdatesExistingTokensAndSavesNewOnes() async throws {
        // test with some uncreated tokens and some pre-existing tokens
    }
    
    @Test("Saving sentence tokens throws error if there is an index collision of a new token with an existing one")
    func saveSentenceTokensThrowsIfIndexCollisionOfNewWithExisting() async throws {
        // criteria for "new" is just that the ID is different
    }
    
    @Test("Clearing sentence tokens clears all of the sentence tokens associated with the article")
    func clearSentenceTokensClearsForOneArticleOnly() async throws {
        // test sentence tokens for multiple articles, and try clearing just one set
    }
    
    @Test("Saving an existing article updates its metadata")
    func saveUpdatesExistingArticle() async throws {
        
    }
    
    @Test("Saving a new article creates it")
    func saveCreatesNewArticle() async throws {
        
    }
    
    @Test("Saving a new article with tags creates any new tags")
    func saveWithTagsCreatesNewTags() async throws {
        // assume there can be a mix of existing + new tags by ID
    }
    
    @Test("Saving a new article with tags having conflicting names with existing tags throws")
    func saveWithTagsHavingConflictingNamesThrows() async throws {
        
    }
    
    @Test("Saving a new article with authors having conflicting names with existing authors throws")
    func saveWithAuthorsHavingConflictingNamesThrows() async throws {
        
    }

    @Test("Deleting an article deletes the article")
    func deleteDeletesTheArticle() async throws {
        
    }
    
    @Test("Deleting an article also deletes its sentence tokens")
    func deleteDeletesSentenceTokens() async throws {
        
    }
    
    @Test("Deleting an article also deletes associated tags if no more articles point to them")
    func deleteDeletesAssociatedTagsIfNoArticlesPointToThem() async throws {
        
    }
    
    // unlike tags, authors do not get automatically deleted
    
    @Test("Deleting an article throws if the article is not found")
    func deleteThrowsIfNotFound() async throws {
        
    }
}
