//
//  FlashcardRepositoryTests.swift
//  KaifangShared
//
//  Created by Brendan Chen on 2026.06.02.
//

import Testing
@testable import KaifangCore
import CoreData

@Suite(.serialized)
struct FlashcardRepositoryTests {
    // MARK: Type aliases
    typealias Flashcard = FlashcardProvider.Flashcard
    typealias FlashcardCreateArguments = FlashcardProvider.FlashcardCreateArguments
    typealias FilterArguments = FlashcardProvider.FilterArguments
    typealias SortCriteria = FlashcardProvider.SortCriteria
    typealias SentenceToken = SegmentationProvider.SentenceToken
    typealias WordToken = SegmentationProvider.WordToken
    typealias Article = ArticleProvider.Article
    typealias Tag = ArticleProvider.Tag
    typealias Author = ArticleProvider.Author

    // MARK: Sample data identity

    /// Stable IDs for the sample articles, index-aligned with ``sampleArticles`` and
    /// ``getSampleArticles()``: index 0 = Alpha, 1 = Bravo, 2 = Charlie. Declared `static` so it
    /// can be referenced from `@Test(arguments:)`, which is evaluated in a static context and so
    /// cannot see instance members — a freshly-minted `UUID()` can't be hardcoded into the
    /// decorator the way the string filters were in ``ArticleRepositoryTests``. Parameterize over
    /// these (they match ``FlashcardProvider/FilterArguments/articleId``) for the articleId filter.
    static let articleIds: [UUID] = [UUID(), UUID(), UUID()]

    // MARK: Setup
    let container: NSPersistentContainer
    let repository: FlashcardRepository

    /// Sample articles, one per entry in ``articleIds`` (`sampleArticles[i].id == articleIds[i]`).
    /// Built once per test case in `init()`, so it stays constant for the lifetime of an
    /// individual test. Use this property for a stable snapshot; ``getSampleArticles()``
    /// regenerates fresh data on each call.
    let sampleArticles: [Article]

    /// Sample flashcards linked to ``sampleArticles`` (plus two orphans with no sentence token).
    /// Built once per test case in `init()` alongside ``sampleArticles`` so their article links
    /// stay consistent and constant for the lifetime of an individual test.
    let sampleFlashcards: [Flashcard]

    init() throws {
        container = try PersistenceController.getTestingContainer()
        repository = FlashcardRepository(container: container)

        let articles = Self.getSampleArticles()
        sampleArticles = articles
        sampleFlashcards = Self.getSampleFlashcards(linkedTo: articles)
    }
    
    // MARK: Test data helpers

    /// Builds the sample articles that ``getSampleFlashcards(linkedTo:)`` links back to. The three
    /// articles (Alpha, Bravo, Charlie) mirror the corresponding entries in
    /// ``ArticleRepositoryTests/getSampleArticles()`` so the bodies match the sentences the
    /// flashcards lift. Each article's `id` is taken from ``articleIds`` at the matching index, so
    /// `result[i].id == articleIds[i]`. Tags, authors, and timestamps are regenerated on each call;
    /// the IDs stay stable. Not persisted — a test that needs the articles in storage saves them
    /// via ``ArticleRepository`` itself.
    static func getSampleArticles() -> [Article] {
        // Generated by Claude

        let newsTag = Tag(id: UUID(), name: "News")
        let techTag = Tag(id: UUID(), name: "Tech")
        let cultureTag = Tag(id: UUID(), name: "Culture")

        let author1 = Author(id: UUID(), name: "Author 1")
        let author2 = Author(id: UUID(), name: "Author 2")
        let author3 = Author(id: UUID(), name: "Author 3")
        let author4 = Author(id: UUID(), name: "Author 4")

        // dateCreated/dateModified must be DISTINCT across articles so date-based sort tests are
        // deterministic — adjacent `Date()` defaults can quantize equal in Core Data storage and
        // produce arbitrary tie-breaking. dateModified must also stay within 0.1s of "now" so
        // CDEntityWithIDAndDateMetadata.willSave's `isCloseToNow` guard doesn't overwrite it.
        let nowReference = Date()
        let createdOffsets: [TimeInterval] = [-3.0, -2.0, -1.0]
        let modifiedOffsets: [TimeInterval] = [-0.003, -0.002, -0.001]

        return [
            // Alpha (articleIds[0]) — transit/news, SC body, unread, single author.
            Article(
                id: articleIds[0],
                plainText: "市议会一致通过新型 buses 巴士拨款议案。该决议将覆盖整个 region 城区的公共交通时间表。下周起新线路开始试运营。",
                title: "Alpha: Transit Budget 公共交通预算获市议会批准",
                datePublished: Date(timeIntervalSince1970: 1_700_000_000),
                dateRead: nil,
                tags: [newsTag],
                authors: [author1],
                dateCreated: nowReference.addingTimeInterval(createdOffsets[0]),
                dateModified: nowReference.addingTimeInterval(modifiedOffsets[0])
            ),
            // Bravo (articleIds[1]) — quantum/tech, TC body, read, co-authored, all three tags.
            Article(
                id: articleIds[1],
                plainText: "研究團隊在會議上展示了穩定的 quantum 量子處理器原型。新架構顯著提升了運算性能與糾錯能力。論文已於本週正式發表。",
                title: "Bravo: Quantum 量子計算重大突破",
                datePublished: Date(timeIntervalSince1970: 1_710_000_000),
                dateRead: Date(timeIntervalSince1970: 1_715_000_000),
                tags: [newsTag, techTag, cultureTag],
                authors: [author1, author2],
                dateCreated: nowReference.addingTimeInterval(createdOffsets[1]),
                dateModified: nowReference.addingTimeInterval(modifiedOffsets[1])
            ),
            // Charlie (articleIds[2]) — culture/festival, TC body, unpublished + unread, co-authored.
            Article(
                id: articleIds[2],
                plainText: "傳統 dance 舞蹈與街頭藝術在開幕表演中亮相。藝術家們吸引了大批熱情的觀眾。活動將持續整整三天。",
                title: "Charlie: Weekend Festival 週末文化節亮點",
                datePublished: nil,
                dateRead: nil,
                tags: [cultureTag],
                authors: [author3, author4],
                dateCreated: nowReference.addingTimeInterval(createdOffsets[2]),
                dateModified: nowReference.addingTimeInterval(modifiedOffsets[2])
            ),
        ]
    }

    /// Builds hand-rolled flashcards representing what a user might create over time. Six link to
    /// one of the three articles passed in — by convention the output of ``getSampleArticles()`` —
    /// via an in-memory ``SegmentationProvider/SentenceToken`` whose `articleId` is the matching
    /// article's `id`; two are orphans with no article link. The sentence tokens are NOT persisted;
    /// a test needing the relationship in Core Data scaffolds the parent article via
    /// ``ArticleRepository`` separately (the article IDs are available as ``articleIds``).
    static func getSampleFlashcards(linkedTo articles: [Article]) -> [Flashcard] {
        // Generated by Claude

        let alphaArticleId = articles[0].id
        let bravoArticleId = articles[1].id
        let charlieArticleId = articles[2].id

        // dateCreated/dateModified must be DISTINCT across flashcards so date-based sort tests
        // are deterministic — adjacent `Date()` defaults can quantize equal in Core Data storage
        // and produce arbitrary tie-breaking. dateModified must also stay within 0.1s of "now" so
        // CDEntityWithIDAndDateMetadata.willSave's `isCloseToNow` guard doesn't overwrite it.
        let nowReference = Date()
        let createdOffsets: [TimeInterval] = [-7.0, -6.0, -5.0, -4.0, -3.0, -2.0, -1.0, 0.0]
        let modifiedOffsets: [TimeInterval] = [-0.007, -0.006, -0.005, -0.004, -0.003, -0.002, -0.001, 0.000]

        // Keyword map for the `contents` filter test. Each test keyword hits exactly one fixture,
        // so expected hit-counts are computable directly from the fixture set.
        //   "buses"    → Alpha 1 originalContext only
        //   "council"  → Alpha 1 wordTranslation + contextTranslation (still single fixture)
        //   "flow"     → Alpha 2 contextTranslation only (English-side hit)
        //   "quantum"  → Bravo 1 originalContext only
        //   "舞蹈"      → Charlie 1 originalWord + originalContext (CJK in both)
        //   "街頭"      → Charlie 1 originalContext only (CJK in context, not word)
        //   "jot"      → Orphan 1 originalContext only (orphan, no article link)
        return [
            // Alpha 1 — newly captured from a news article, never reviewed yet.
            Flashcard(
                id: UUID(),
                dueDate: nowReference.addingTimeInterval(-2 * 86_400),
                easeFactor: 2.5,
                interval: 0,
                lastReviewedAt: nil,
                repetitions: 0,
                sentenceToken: SentenceToken(
                    id: UUID(),
                    articleId: alphaArticleId,
                    articleTextPositionStart: 0,
                    sentenceIndexInArticle: 0,
                    tokenText: "市议会一致通过新型 buses 巴士拨款议案。",
                    wordTokens: [
                        WordToken(id: UUID(), tokenText: "市议会", sentenceTextPositionStart: 0, wordIndexInSentence: 0)
                    ]
                ),
                originalWord: "市议会",
                originalContext: "市议会一致通过新型 buses 巴士拨款议案。",
                wordTranslation: "city council",
                contextTranslation: "The city council unanimously approved the new bus funding bill.",
                dateCreated: nowReference.addingTimeInterval(createdOffsets[0]),
                dateModified: nowReference.addingTimeInterval(modifiedOffsets[0])
            ),
            // Alpha 2 — struggling card from the same article: failed it once, low ease, learning phase.
            Flashcard(
                id: UUID(),
                dueDate: nowReference.addingTimeInterval(3 * 86_400),
                easeFactor: 1.7,
                interval: 1,
                lastReviewedAt: nowReference.addingTimeInterval(-86_400),
                repetitions: 1,
                sentenceToken: SentenceToken(
                    id: UUID(),
                    articleId: alphaArticleId,
                    articleTextPositionStart: 25,
                    sentenceIndexInArticle: 1,
                    tokenText: "该决议将覆盖整个 region 城区的公共交通时间表。",
                    wordTokens: [
                        WordToken(id: UUID(), tokenText: "公共交通", sentenceTextPositionStart: 18, wordIndexInSentence: 7)
                    ]
                ),
                originalWord: "公共交通",
                originalContext: "该决议将覆盖整个 region 城区的公共交通时间表。",
                wordTranslation: "public transit",
                contextTranslation: "The resolution covers public transit schedules across the entire flow region.",
                dateCreated: nowReference.addingTimeInterval(createdOffsets[1]),
                dateModified: nowReference.addingTimeInterval(modifiedOffsets[1])
            ),
            // Alpha 3 — same article, two reviews in, mid ease, contextTranslation not filled in yet.
            Flashcard(
                id: UUID(),
                dueDate: nowReference.addingTimeInterval(-1 * 86_400),
                easeFactor: 2.3,
                interval: 1,
                lastReviewedAt: nowReference.addingTimeInterval(-2 * 86_400),
                repetitions: 2,
                sentenceToken: SentenceToken(
                    id: UUID(),
                    articleId: alphaArticleId,
                    articleTextPositionStart: 50,
                    sentenceIndexInArticle: 2,
                    tokenText: "下周起新线路开始试运营。",
                    wordTokens: [
                        WordToken(id: UUID(), tokenText: "试运营", sentenceTextPositionStart: 9, wordIndexInSentence: 5)
                    ]
                ),
                originalWord: "试运营",
                originalContext: "下周起新线路开始试运营。",
                wordTranslation: "trial operation",
                contextTranslation: nil,
                dateCreated: nowReference.addingTimeInterval(createdOffsets[2]),
                dateModified: nowReference.addingTimeInterval(modifiedOffsets[2])
            ),
            // Bravo 1 — from a tech/quantum article (TC). Review phase, default ease, six-day interval.
            Flashcard(
                id: UUID(),
                dueDate: nowReference.addingTimeInterval(7 * 86_400),
                easeFactor: 2.5,
                interval: 6,
                lastReviewedAt: nowReference.addingTimeInterval(-86_400),
                repetitions: 4,
                sentenceToken: SentenceToken(
                    id: UUID(),
                    articleId: bravoArticleId,
                    articleTextPositionStart: 0,
                    sentenceIndexInArticle: 0,
                    tokenText: "研究團隊在會議上展示了穩定的 quantum 量子處理器原型。",
                    wordTokens: [
                        WordToken(id: UUID(), tokenText: "量子", sentenceTextPositionStart: 24, wordIndexInSentence: 10)
                    ]
                ),
                originalWord: "量子",
                originalContext: "研究團隊在會議上展示了穩定的 quantum 量子處理器原型。",
                wordTranslation: "quantum",
                contextTranslation: nil,
                dateCreated: nowReference.addingTimeInterval(createdOffsets[3]),
                dateModified: nowReference.addingTimeInterval(modifiedOffsets[3])
            ),
            // Bravo 2 — mature card from same article, high ease, originalContext intentionally
            // omitted to model "I trimmed the context after I knew the word cold."
            Flashcard(
                id: UUID(),
                dueDate: nowReference.addingTimeInterval(30 * 86_400),
                easeFactor: 2.9,
                interval: 14,
                lastReviewedAt: nowReference.addingTimeInterval(-7 * 86_400),
                repetitions: 5,
                sentenceToken: SentenceToken(
                    id: UUID(),
                    articleId: bravoArticleId,
                    articleTextPositionStart: 28,
                    sentenceIndexInArticle: 1,
                    tokenText: "新架構顯著提升了運算性能與糾錯能力。",
                    wordTokens: [
                        WordToken(id: UUID(), tokenText: "糾錯", sentenceTextPositionStart: 12, wordIndexInSentence: 8)
                    ]
                ),
                originalWord: "糾錯",
                originalContext: nil,
                wordTranslation: "error correction",
                contextTranslation: nil,
                dateCreated: nowReference.addingTimeInterval(createdOffsets[4]),
                dateModified: nowReference.addingTimeInterval(modifiedOffsets[4])
            ),
            // Charlie 1 — culture article (TC), brand new, never reviewed, due right now.
            Flashcard(
                id: UUID(),
                dueDate: nowReference,
                easeFactor: 2.0,
                interval: 0,
                lastReviewedAt: nil,
                repetitions: 0,
                sentenceToken: SentenceToken(
                    id: UUID(),
                    articleId: charlieArticleId,
                    articleTextPositionStart: 0,
                    sentenceIndexInArticle: 0,
                    tokenText: "傳統 dance 舞蹈與街頭藝術在開幕表演中亮相。",
                    wordTokens: [
                        WordToken(id: UUID(), tokenText: "舞蹈", sentenceTextPositionStart: 9, wordIndexInSentence: 2)
                    ]
                ),
                originalWord: "舞蹈",
                originalContext: "傳統 dance 舞蹈與街頭藝術在開幕表演中亮相。",
                wordTranslation: "dance",
                contextTranslation: "Traditional dance and street art appeared in the opening performance.",
                dateCreated: nowReference.addingTimeInterval(createdOffsets[5]),
                dateModified: nowReference.addingTimeInterval(modifiedOffsets[5])
            ),
            // Orphan 1 — manually jotted down outside any article, kept being forgotten (ease 1.3).
            Flashcard(
                id: UUID(),
                dueDate: nowReference.addingTimeInterval(-5 * 86_400),
                easeFactor: 1.3,
                interval: 30,
                lastReviewedAt: nowReference.addingTimeInterval(-3 * 86_400),
                repetitions: 8,
                sentenceToken: nil,
                originalWord: "流动性",
                originalContext: "I want to jot this down — the liquidity story is everywhere.",
                wordTranslation: "liquidity",
                contextTranslation: nil,
                dateCreated: nowReference.addingTimeInterval(createdOffsets[6]),
                dateModified: nowReference.addingTimeInterval(modifiedOffsets[6])
            ),
            // Orphan 2 — manually added long ago, very mature, no translations filled in.
            Flashcard(
                id: UUID(),
                dueDate: nowReference.addingTimeInterval(14 * 86_400),
                easeFactor: 3.2,
                interval: 90,
                lastReviewedAt: nowReference.addingTimeInterval(-30 * 86_400),
                repetitions: 12,
                sentenceToken: nil,
                originalWord: "宁静",
                originalContext: nil,
                wordTranslation: nil,
                contextTranslation: nil,
                dateCreated: nowReference.addingTimeInterval(createdOffsets[7]),
                dateModified: nowReference.addingTimeInterval(modifiedOffsets[7])
            ),
        ]
    }

    // MARK: Finding and lookup
    @Test("Finding a flashcard returns from storage")
    func findReturnsFromStorage() async throws {
        let flashcards = sampleFlashcards

        for flashcard in flashcards {
            let expectedFlashcard = try await repository.save(flashcard)
            let resultFlashcard = try await repository.find(flashcard.id)
            #expect(expectedFlashcard == resultFlashcard)
        }
    }
    
    @Test("Finding a flashcard returns nil if not found")
    func findReturnsNilIfNotFound() async throws {
        let resultFlashcard = try await repository.find(UUID())
        #expect(resultFlashcard == nil)
    }
    
    // MARK: Listing, filtering and sorting
    struct FilterCase: Sendable {
        let name: String
        let filterBy: @Sendable (Flashcard) -> Bool
        let criteria: FilterArguments
    }
    
    @Test(
        "Different filtering options return the expected outputs",
        arguments: [
            FilterCase(
                name: "Filter by article ID returns blank array if no article ID",
                filterBy: { _ in false },
                criteria: FilterArguments(
                    articleId: UUID(),
                    dueOnly: nil,
                    contents: nil
                )
            )
        ]
    )
    func filterOptionsReturnExpectedOutputs(filterCase: FilterCase) async throws {
        
    }
    
    struct SortCase: Sendable {
        let name: String
        let sortBy: @Sendable (Flashcard, Flashcard) -> Bool
        let criteria: SortCriteria
    }
    
    @Test(
        "Different sorting options return the expected outputs",
        arguments: [
            SortCase(
                name: "Sorting by ascending due date returns earliest due dates first",
                sortBy: { $0.dueDate > $1.dueDate },
                criteria: .dueDate(.forward),
            ),
            SortCase(
                name: "Sorting by descending due date returns latest due dates first",
                sortBy: { $0.dueDate < $1.dueDate },
                criteria: .dueDate(.reverse)
            ),
            SortCase(
                name: "Sorting by ascending date modified returns least recently modified first",
                sortBy: { $0.dateModified < $1.dateModified },
                criteria: .dateModified(.forward)
            ),
            SortCase(
                name: "Sorting by descending date modified returns most recently modified first",
                sortBy: { $0.dateModified > $1.dateModified },
                criteria: .dateModified(.reverse)
            ),
            SortCase(
                name: "Sorting by ascending date created returns oldest first",
                sortBy: { $0.dateCreated < $1.dateCreated },
                criteria: .dateModified(.reverse)
            ),
            SortCase(
                name: "Sorting by descending date created returns newest first",
                sortBy: { $0.dateCreated > $1.dateCreated },
                criteria: .dateModified(.reverse)
            ),
        ]
    )
    func sortOptionsReturnExpectedOutputs(sortCase: SortCase) async throws {
        
    }
    
    // MARK: Saving
    @Test("Saving an existing flashcard updates it")
    func saveExistingUpdates() async throws {
        
    }
    
    @Test("Saving a new flashcard creates it")
    func saveNewCreates() async throws {
        
    }
    
    // MARK: Deleting
    @Test("Deleting a flashcard removes it from storage")
    func deleteRemovesFromStorage() async throws {
        
    }
    
    @Test("Deleting throws if the flashcard is not found in storage")
    func deleteThrowsIfFlashcardNotFound() async throws {
        
    }
    
    @Test("Clearing does not clear other data types")
    func clearOnlyClearsFlashcards() async throws {
        
    }
}
